### ISSUE TITLE
CMake write script

### ISSUE THREAD

**Issue by UnkDevE** [EthanRiley/SKSEBot#2]
Cmake script needs the correct library(boost regex) and needs pesudocode to be checked.
After needs to be tested

**Comment by UnkDevE** [comment]
@Jamierocks once the Script is finished could you test it as your on mac( then we get to test all OS'ses )

**Comment by jamierocks** [comment]
Sure :)

**Comment by UnkDevE** [comment]
finished it 
lets go

**Comment by UnkDevE** [comment]
cmake gives error Function missing opening "("

**Comment by jamierocks** [comment]
Could you post the whole log? I will test now :)

**Comment by UnkDevE** [comment]
re post changes made some errors in code but not much ; sill does not work though heres log:
CMake Error: Error in cmake code at
C:/Users/Ethan/Documents/Visual Studio 2015/SKSEBot-master/CMakeLists.txt:0:
Parse error.  Function missing opening "(".
Configuring incomplete, errors occurred!
Truly meaningless as there is a '(' on the fist (or zeroth line)

converted to ansci still does not work
think newlines arent being read corectly - tested on notepad no newlines notepad++ newlines

**Comment by UnkDevE** [comment]
endif -> endif() syntax incorrect :(

**Comment by UnkDevE** [comment]
fixed needs to add GUI input for boost though

**Comment by UnkDevE** [comment]
close issue add new [Testing](https://github.com/EthanRiley/SKSEBot/issues/3)
