### ISSUE TITLE
Testing cmake File

### ISSUE THREAD

**Issue by UnkDevE** [EthanRiley/SKSEBot#3]
need to test cmake file on all OS'ses 
add gui for adding boost dir

**Comment by UnkDevE** [comment]
@jamierocks cmake fixed please check on your machine

**Comment by jamierocks** [comment]
I am assuming boost is available as a Git (or Git compatible repository), why not use a submodule?

**Comment by UnkDevE** [comment]
good point but boost is too large and needs a completely different build step of its own in some cases and cannot provide OS wide - like the cmake does 
[see here for more details](http://www.boost.org/doc/libs/1_58_0/more/getting_started/windows.html)

**Comment by jamierocks** [comment]
Boost's source code would seem to be avaliable through [SourceForge](http://sourceforge.net/p/boost/code/?source=navbar), and uses [CVS](http://www.nongnu.org/cvs/).

CVS would seem to be compatible with Git, as can be seen by their [documentation](http://git-scm.com/docs/git-cvsimport). However as noted by their documentation you may wish to use [parsecvs](https://github.com/BartMassey/parsecvs) as an alternative.

If you are wondering about the [GitHub importer](https://import.github.com/new), it would seem it only supports SVN, Hg or TFS repositories.

As an example of a ported repository, I made a Git mirror of [LiteLoader](http://www.liteloader.com/), avaliable on [GitHub](https://github.com/jamierocks/LiteLoaderMirror). However this is a clone of a subversion repository.

**Comment by jamierocks** [comment]
Now I've read your above comment, you can safely discard the above comment. :)

**Comment by UnkDevE** [comment]
boost does have repository but as their 'superpository' cloning it would not be a good idea 
and again my above comment applies too

**Comment by UnkDevE** [comment]
saying that it is made up of lots of little repositories but this is still devoid the point as it might confilict with already installed boost versions as cmake uses environment variables set by boost

**Comment by jamierocks** [comment]
I am merely pointing this out, however Gradle has quite nice native C/C++ now.
http://gradle.org/getting-started-native/

**Comment by UnkDevE** [comment]
or not even work at all

**Comment by UnkDevE** [comment]
comment was for above. Gradle looks very good indeed although cmake may make it pointless now

**Comment by jamierocks** [comment]
At the moment Gradle's native support is much smaller than that of their Java support. For that I would suggest you use cmake, just keep a close eye on Gradle. :)

**Comment by UnkDevE** [comment]
yeah sometime soon it might be the better of the two, but they are basically the same thing;
cmake is just more;manual.
back on task, have you tested this yet?

**Comment by jamierocks** [comment]
When you have something available to get Boost I will give it a test. :)

This is what Gradle is great for. Perhaps try out gulp.js

**Comment by UnkDevE** [comment]
ok ta build seems good at work exp

**Comment by jamierocks** [comment]
Awesome, is Tom doing work experience too?

**Comment by UnkDevE** [comment]
yeah have you tested yet. work exp is really interesting.

**Comment by UnkDevE** [comment]
<sigh> but i cannot tell you what i am doing (council rules protecting information)

**Comment by UnkDevE** [comment]
updated cmake so can be manually inputted the boost path if finding the path went wrong

**Comment by UnkDevE** [comment]
closing issue as have tested so that cmake works now moving on cmake Test builds as the cmake is not the issue

**Comment by jamierocks** [comment]
Now it's definately not cross-compatible :P
